/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team1.client;

import java.io.BufferedReader;
import java.io.EOFException;
import java.io.IOError;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.lang.ModuleLayer.Controller;
import java.nio.Buffer;
import java.util.ArrayList;
import java.util.List;
import java.io.IOException;
import edu.duke.ece651.team1.shared.MyName;
import edu.duke.ece651.team1.shared.Student;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;
import edu.duke.ece651.team1.client.controller.*;
// @SpringBootApplication
import edu.duke.ece651.team1.client.model.UserSession;
import java.net.InetAddress;


public class App {

  public static void main(String[] args) throws IOException{
    BufferedReader inputReader = new BufferedReader(new InputStreamReader(System.in));
    ApplicationController controller = new ApplicationController(inputReader, System.out);
    InetAddress inetAddress = InetAddress.getLocalHost();
    UserSession.getInstance().setHost(inetAddress.getHostName());
    UserSession.getInstance().setPort("8080");
    controller.startApplication();
  }
}
